### ISSUE TITLE
Всё пропало!!!

### ISSUE THREAD

**Issue by redboo** [syeysk/svg2animation#3]
```shell
Processing: files/Flag_of_Kaltan.svg
Traceback (most recent call last):
  File "/home/redboo/code/svg2animation/svg2anima.py", line 58, in <module>
    svg2animation(input_file, output_file, args.packer, args.fps, args.duration, args.width, args.height)
  File "/home/redboo/code/svg2animation/svg2anima.py", line 27, in svg2animation
    for frame in frame_iterator(simple_svg, scale):
  File "/home/redboo/code/svg2animation/main_variant2.py", line 221, in frame_iterator
    png_file = svg_data2png(
  File "/home/redboo/code/svg2animation/main_variant2.py", line 103, in svg_data2png
    cairosvg.svg2png(
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairosvg/surface.py", line 133, in convert
    instance = cls(
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairosvg/surface.py", line 204, in __init__
    self.cairo, self.width, self.height = self._create_surface(
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairosvg/surface.py", line 525, in _create_surface
    cairo_surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairocffi/surfaces.py", line 735, in __init__
    Surface.__init__(self, pointer, target_keep_alive=data)
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairocffi/surfaces.py", line 158, in __init__
    self._check_status()
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairocffi/surfaces.py", line 170, in _check_status
    _check_status(cairo.cairo_surface_status(self._pointer))
  File "/home/redboo/code/svg2animation/env/lib/python3.10/site-packages/cairocffi/__init__.py", line 87, in _check_status
    raise exception(message, status)
cairocffi.CairoError: cairo returned CAIRO_STATUS_INVALID_SIZE: b'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'
```

Assignees: Polyakov Konstantin
Labels: bug

**Comment by redboo** [comment]
lines 164,165
```
    source_width = float(dom_svg.childNodes[0].attributes.get("width").value.rstrip("pt"))
    source_height = float(dom_svg.childNodes[0].attributes.get("height").value.rstrip("pt"))
```
